# -*- coding: utf-8 -*-
"""Assignment3_21EC39023_evaluator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CuBEV7WS-7tDr3S6Z6BTcwe8qosexVS1
"""

!pip install rouge_score

import pandas as pd
import json
from rouge_score import rouge_scorer

# Step 1: Read CSV, convert to dictionary, and save as TXT
df = pd.read_csv("/content/Assignment3_21EC39023_summary.csv")
summary_dict = df.set_index('id').to_dict(orient='index')

with open("summaries.txt", "w") as f:
    json.dump(summary_dict, f)

with open("summaries.txt", "r") as f:
    loaded_dict = json.load(f)

loaded_df = pd.DataFrame.from_dict(loaded_dict, orient='index').reset_index()
loaded_df.columns = ['id', 'original_sentences', 'generated_summary']
loaded_df.to_csv("reconstructed_summaries.csv", index=False)

scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2'], use_stemmer=True)

rouge_scores = []

for _, row in loaded_df.iterrows():
    original = row['original_sentences']
    generated = row['generated_summary']

    # Compute ROUGE-1 and ROUGE-2
    scores = scorer.score(original, generated)
    rouge_scores.append({
        'id': row['id'],
        'rouge1': scores['rouge1'].fmeasure,
        'rouge2': scores['rouge2'].fmeasure
    })

rouge_scores_df = pd.DataFrame(rouge_scores)
rouge_scores_df.to_csv("Assignment3_21EC39023_scores.csv", index=False)