# -*- coding: utf-8 -*-
"""Assignment1_21EC39023_parser

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dhq6bLM4q40o6SH7aGo8e1pCJ1ZH0dDS
"""

import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):
    stop_words = set(stopwords.words('english'))
    lemmatizer = WordNetLemmatizer()


    text = re.sub(r'[^\w\s]', '', text)


    tokens = [word for word in text.lower().split() if word not in stop_words]


    tokens = [lemmatizer.lemmatize(word) for word in tokens]

    return tokens

def preprocess_query_file(query_path):
    queries = []

    with open(query_path, 'r') as file:
        query_id = None
        for line in file:
            if line.startswith('.I'):
                query_id = line.split()[1]
            elif line.startswith('.W'):
                text = next(file).strip()
                tokens = preprocess_text(text)
                query_text = ' '.join(tokens)
                queries.append(f"{query_id}\t{query_text}")

    with open(f'queries_21EC39023.txt', 'w') as f:
        f.write('\n'.join(queries))

    # Printing a portion of the processed queries
    print("Sample of the Processed Queries:")
    for query in queries[:1000]:  # Print the first 10 queries
        print(query)

if __name__ == "__main__":
    import sys
    query_path = sys.argv[1]
    preprocess_query_file(query_path)